spring:
  application:
    name: spring-security
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/authenticated_users
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  config:
    import: optional:token-key.properties
server:
  port: 8091
